Update to kubernetesmgr/resources
FNNDSC/pman pull request #219
Opened 2022-12-09 06:23 UTC by lilloukas

Adding in changes to kubernetesmgr and resources so that pman works on OpenShift with a named PVC. 'STORAGE_TYPE' environment manual needs to be something other than 'host' or 'nfs', and 'CONTAINER_ENV' needs to be set as 'kubernetes'

2022-12-12 18:09 UTC, jennydaman requested changes

2022-12-12 18:09 UTC, jennydaman commented on pman/resources.py
> +        logger.info(f'command: {cmd}')
this debugging statement shouldn't be left here (unless you also print out which jid it's for)

2022-12-12 18:09 UTC, jennydaman commented on pman/resources.py
> +                                           args.env,share_dir)
:(

2022-12-12 18:09 UTC, jennydaman commented on pman/resources.py
> +            input_dir = f'/share/key-{job_id}/incoming'
code could be cleaned up here because only `input_dir` and `output_dir` are different between these if/else branches

2022-12-12 18:09 UTC, jennydaman commented on pman/resources.py
> +            storage_type: str
tempted to think about a solution using dynamic dispatch

2022-12-12 18:09 UTC, jennydaman commented
Also, be sure to update the docs (README) when you make a change to behavior

2022-12-22 08:26 UTC, lilloukas commented on pman/resources.py
> +            storage_type: str
I'm not sure what change would be implemented here to make that happen, so I haven't updated this part.

2023-04-28 10:11 UTC, jennydaman commented
Closed in favor of #228

2023-04-28 10:11 UTC, closed without merging